### PR TITLE
Parse setup keyword arg for testitems to include a shared test setup …

### PR DESCRIPTION
**Pull request by quinnj**
…module

### CODE REVIEW

**Review by davidanthoff — COMMENTED** [review]
I think we would ideally handle this in one function? So essentially just move the code that you added in `find_test_setups_detail!` as a third `elseif` top-level branch to the existing `find_test_items_detail!` functions, and then change the name and signature of that to
```
function find_test_detail!(node, testitems, testsetups, errors)
```
That way we would only have to traverse the syntax tree once, and I don't think there is ever a scenario where we wouldn't want to extract both test item and setup info at the same time?

**Comment by davidanthoff** [comment]
@quinnj I just pushed a commit here that merges the two functions, and I fixed the tests. I'm going to merge once CI passes, it should be much easier then to continue in the other parts if this is just on `main` with the git submodule stuff.

**Comment by quinnj** [comment]
Great timing! I was about to sit down and do it, so that sounds great.

**Comment by davidanthoff** [comment]
Once this is merged we still need some tests for the new `@testsetup` stuff, but I think that can come in a later PR.

**Pull request merged**
